name: Benchmarks

on:
  workflow_dispatch:
  pull_request:
    branches:
      # workflow dispatch cannot be triggered off the main branch,
      # so we have this one execption
      - bench

jobs:
  benchmark:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Rust
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        toolchain: stable
    
    - name: Run benchmarks
      run: cargo bench --bench rule_engines
    
    - name: Upload benchmark results
      uses: actions/upload-artifact@v4
      with:
        name: benchmark-results
        path: target/criterion/
        retention-days: 30
