name: Benchmarks

on:
  workflow_dispatch:
  pull_request:
    branches: [main]
    paths:
      - 'src/rules/**'
      - 'benches/**'
      - '.github/workflows/benchmark.yml'

jobs:
  benchmark:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Rust
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        toolchain: stable
    
    - name: Run benchmarks
      run: cargo bench --bench rule_engines
    
    - name: Generate pprof profile for proc_engine
      run: cargo run --release --example profile_proc --features profile
    
    - name: Upload benchmark results
      uses: actions/upload-artifact@v4
      with:
        name: benchmark-results
        path: |
          target/criterion/
          profile.pb.gz
        retention-days: 30