name: Linux Tests with Cleanup

on:
  workflow_call:

jobs:
  test:
    runs-on: [self-hosted, linux]
    steps:
      - uses: actions/checkout@v4
      
      - name: Pre-test cleanup
        run: |
          echo "Running pre-test cleanup to ensure clean state..."
          sudo bash scripts/ci-cleanup.sh || true
          
      - name: Run tests
        run: |
          sudo -E cargo nextest run --test linux_integration --no-fail-fast
          
      - name: Post-test cleanup
        if: always()
        run: |
          echo "Running post-test cleanup..."
          sudo bash scripts/ci-cleanup.sh || true